### PR TITLE
WIP: Add multichannel support

### PR DESCRIPTION
**Pull request by hagau**
This adds the ability to use multiple radio modules in the middleware, each on a fixed channel, and allows for selecting the proper channel based on the ITS-AID of the geonet request.

### CODE REVIEW

**Comment by riebl** [comment]
@hagau Thanks for this PR! I briefly skimmed the changes and like them mostly. However, I wonder if we can find a less complex solution for the RadioManager + RadioModule + RadioDriver + NIC conglomerate. I fear this makes it extremely hard (especially for newbies) to understand the packet data flow.

**Comment by hagau** [comment]
@riebl 
It's not much different than before and should be obvious from the station module definition, e.g. from *Car.ned* and reading ``initializeGeoNetworking()`` in the ``Middleware``. 

``Middleware`` <-> *(Geo)*``Router`` <-> ``RadioModule`` <-> ``RadioDriver`` <-> ``IWirelessNic.mac``

 Of course, I'm biased from having worked on it for some time :)

The idea was that a ``RadioModule`` could use any kind of RadioDriver (ITS-G5, LTE, ...), present an interface for GeoRouter to use and otherwise implement the media-dependant stuff that doesn't fit anywhere else. Granted, with RadioModule having a mandatory channel and link layer address this general approach is not sensible anymore. 
So now ``ItsRadioModule`` pretty much just does congestion control. I'm not sure where this functionality would be better placed.
(A separate ``ItsRadioModule`` also allows for setting the length of the DCC queue independently for each module/channel without much additional code. I'm not sure if this is of much use though)

I should definitely add some documentation.

**Comment by riebl** [comment]
I have following remarks after looking through your code:

- First of all, thanks for your effort to contribute MCO to Artery :-)
- `RadioTable::ChannelList`: Maybe a set would be a more appropriate basic type. Possibly rename `ChannelList` to `Channels then.
- I suggest to extract all antenna properties from `RadioModule` to a dedicated class. This also simplifies reading those properties directly from INET antennas in the future.
- I would like to have a default channel to be used when a service does not demand a particular one. Hence, I favour to keep the `ItsG5Service::request` without enforcing a channel parameter to be set, e.g. defaulting to `boost::none` implicitly.
- Move classes such as `McoStrategy` etc. to a better fitting directory (mco?) because those are not really applications or closely related to applications at all. I know that there are already some non-application classes located there, but that's just legacy ;-)
- `DccFacility`: Why is a list of schedulers/state machines returned for one channel?
- Might `DccFacility` just be an interface implemented by `ItsRadioModule` and exposed to services?
- Merge `RadioDriver` and `RadioModule`? It is quite suspicious to have two modules with similar yet generic names. I assume only minor changes to `RadioDriver` would be needed as soon as antenna properties are extracted :-)

Of course, my remarks are to be discussed because I may have missed some circumstances where my proposed changes would worsen things.

**Comment by hagau** [comment]
Sorry for the late reply, there's a lot to unpack :)

- `RadioTable::ChannelList`: I assume you mean `RadioTable::RadioModuleList` and `McoStrategy::ChannelList`, in general the use of a `std::vector` instead of a more fitting `std::set`.
I was thinking a `std::set` would be less efficient since there are mostly 1-4 `RadioModules` in the list and iterating over a short, contiguous array is faster than walking a tree. This may not really matter here. I'll change it to a set.

- antenna properties: I was not sure whether extracting the antenna config to a separate class might be necessary, but the `AntennaType` type tag nonsense has to go :).

- default channel: I keep forgetting about default arguments. `boost::none` is now the default value for the `radioModules` argument of `ItsG5Service::request` & `ItsG5BaseService::request`

- `DccFacility`:
  - multiple scheduler: There could be more than one `RadioModule` tuned to a channel, maybe because these `RadioModule`s have a directional antenna attached instead of a isotropic one. (Maybe in this case the `RadioModule`'s DccScheduler should be shared? Then again, (at least for stationary objects) the partial view of the channel utilisation is 'right'. Really, this should be up to the user, therefore a separate `DccScheduler` module would be necessary, complicating the design further...)
  - `DccFacility` as interface of `RadioModule`
 Well, yes. One could get the desired `RadioModule`s via `RadioTable::get` and then get the `DccScheduler`/`DccStateMachine` from the RadioModule. `DccFacility` is just there to provide a convenient interface and reduce code repetition.

I'll get to the other remarks shortly.

**Comment by hagau** [comment]
- Merging `RadioDriver` & `RadioModule`: Yes, that seems like a good idea. I'll have to think about the interface to the `Middleware` though:
`GeoRouter` needs a `dcc::RequestInterface` as output, so either add that to `InetRadioDriver` or move the `GeoRouter` into `InetRadioDriver` and use gates.

**Comment by hagau** [comment]
- regarding `DccFacility`:
Actually, every time I looked at `inet.Car`, I forgot why I made `DccFacility` a separate module :). In the current implementation, there's no need for that. So moving the getter for `DccScheduler`/`DccStateMachine` to `RadioTable` and defining `DccFacility` as an interface of `RadioDriver` cleans this up nicely.

- regarding `GeoRouter`:
I might just wrap `GeoRouter` with a dummy `dcc::RequestInterface` that only packages the request and sends it via a gate to the desired `RadioDriver`.

**Comment by riebl** [comment]
Wrapping `GeoRouter` is a good idea! In fact, this supports our long-term goal to make the ITS-G5 stack exchangeable.

**Comment by hagau** [comment]
Ok, I've rebased my changes on master & simplified the transceiver selection. There's now a 1-to-1 relation between channel and transceiver, which should be sufficient for now.
The network initialisation is not pretty. I'm thinking maybe adding an `InitStage` for networking.

**Comment by hagau** [comment]
- I've added `InitStages::Networking` & `InitStages::Services`  
  - `Router` & `DccEntity` register themselves in their respective facilities in `InitStages::Networking`
- Right now, I'm setting the GeoNetworking address of all GeoRouter of a vehicle to the same value, but at the INET level there's no way to set the link-layer address.  
That means the receiving side sees the wrong address  
=> `MID` != `ll.src_addr` even for SHB to broadcast.  
Curiously, the entries in the `LocationTable` are correct since insertion happens via `LongPositionVector`(-> `MID`), but retrieval happens with the `ll.src_addr` (-> no entry).  
If one implements a 1<->1-mapping of address<->channel, this problems solves itself. 
I think that would be preferable as default?

**Comment by hagau** [comment]
Further changes:  
- minimal Veins support, single channel only. Seems to be functional (-> runs; I don't know/use Veins)
- more robust initialisation

**Comment by riebl** [comment]
@hagau first of all, thanks for your patience and great work!
I have refactored your `hagau:multichannel` branch and pushed it to my `multichannel` branch. 
Brief summary about my changes:
- rename a few things, e.g. "PromiscuousHook" to "TappingInterface")
- McoStrategy became MultiChannelPolicy with slightly different internals
- keep backward-compatibility with previous service interface
- simplified design by introducing `TransportDispatcher`, a channel-aware BTP port dispatcher

Please, have a look at it and give me feedback. I am particularly interested if this branch is still powerful enough for your simulation purposes or lacking a required feature.
Also, please feel free to update the comment header of each file to include your name in the copyright notice where appropriate.

**Comment by hagau** [comment]
@riebl Thank you, your `multichannel` branch looks great (I've done a test run with Address-/UBSanitizer as usual) and has all the required features for our purposes :+1:. 
Just one note: I've updated the workaround patch in https://github.com/riebl/artery/pull/27. I had missed the changes in a3131466429ccd2e4b44a9c3a7eda65484e7e150 before.

**Comment by riebl** [comment]
Merged as per aa98fbcac807cfe0d23fb0c7b1448c7f04f20e22. Thanks again for your contribution!

**Pull request closed without merging**
