### PR TITLE
Updated Submodule pybind11 to latest commit in order to fix build-error 

### PR DESCRIPTION
**Pull request by Enough7**
closes riebl/artery#297

### CODE REVIEW

**Comment by riebl** [comment]
Is there any reason why we should not update to the most recent pybind11 release?

**Comment by riebl** [comment]
I have noticed that pybind11 suggests to compile with `-fvisibility=hidden`. So I have updated pybind11 to v2.11.1 and introduced a shared library API mechanism for our *storyboard* library. Can you @Enough7 please check if my branch *pybind11_update* works for you too?

**Comment by Enough7** [comment]
Hi @riebl,
I tested the following input:
```console
git clone https://github.com/riebl/artery.git
cd artery/
git checkout pybind11_update
git submodule update --init --recursive
mkdir build
cd build
cmake ..
cmake --build . --parallel 12
cd ..
cmake --build build --target run_example
``` 
Then started and finished the simulation and closed artery.
No errors were reported.

**Comment by riebl** [comment]
Great, thanks for your feedback. I have just merged the pybind11 update into master.

**Pull request closed without merging**
