### PR TITLE
envmod: rework of sensor abstraction and configuration

### PR DESCRIPTION
**Pull request by awillecke**
Hi Raphael,

I've been working on reorganizing the sensors to enable more fine-granular configuration and evaluation.
I'm would like to get your thoughts on this and any feedback is appreciated.

Here is an overview of what will change:
The previous RadarSensor is now the more general FovSensor, which is extended by the RadarSensor and by the new OmniscientSensor. The RadarSensor specifies the sensor category and LoS checks for a FovSensor. The new OmniscientSensor is a FovSensor with a 360 dregree view and of category 'omniscient' that does not perform LoS checks.
This sensor may be useful for awareness evaluations.

Additionally, sensors can be named to distinguish them from each other, even when they are of the same type. The name can be set using the XML attribute `name`. To determine objects detected by a sensors with given name, the function `filterBySensorName` of the LocalEnvironmentModel can be used. This is now used in the EnvmodPrinter service as well.

An example of the new sensor configuration is shown in the artery scenario.

Regards
Alexander

### CODE REVIEW

**Comment by riebl** [comment]
Hi Alexander,

I like your changes, especially the addition of configurable sensor names.
Regarding the `OmniscientSensor` I am wondering if this is actually a `FovSensor` because it has no restricted field of view and is also not affected by line of sight obstructions. Also, a sensor position is irrelevant for such an omniscient sensor. I love this name, though ;-)

Along with the refactoring of FoV sensors, we should also adjust `GlobalEnvironmentModel::detectObjects`: Instead of passing a `SensorConfigRadar` object, it might be beneficial to have a more flexible interface also supporting new sensor types easily. For example, `OmniscientSensor` should not need to approximate a circle by 12 segments; simple range checks would be sufficient for this sensor type.
Maybe passing a `std::function<>` as a parameter to `detectObjects` would be nice that can access `GlobalEnvironmentModel`'s r-tree and alike read-only. Then all the sensor-specific logic can be removed from `GlobalEnvironmentModel`. What do you think?

Regards,
Raphael

**Comment by awillecke** [comment]
Hi Raphael,

thank you for your feedback.

For the `GlobalEnvironmentModel::detectObjects` to use a function of the specific sensor to determine detected objects instead of the sensor configuration is a great idea. I will work on that as soon a I find some time.

Regarding the omniscient sensor, I agree that the perception with a simple range check would be a lot easier to compute than the inclusion in a polygon. But only if the the omniscient sensor is always a 360 degree sensor. I also think it would make sense for it to have an FoV in cases you want o evaluate something like awareness increase due to CAMs and such. Therefore, the normal radar sensors could be "overlayed" with omniscient sensors to get more realistic information about obstructions. If you are not convinced that this is necessary or needed, of course I can also rework the omniscient sensor to just use distance check.
Maybe an additional sensor could also be a third solution, if a fast 360 degree sensor is desired.

Regards
Alexander

**Comment by awillecke** [comment]
Hi Raphael,

I've found some time to hopefully finish the rework.

The detections of a sensor are now determined by the `detectObjects` function implemented by the sensor which is then passed to the `GlobalEnvironmentModel` as you suggested (or at least how I understood it).

Also, I cleaned up the sensors by adding parameters allowing for some classes to be removed, while keeping backward-compatibility.

Looking forward to your feedback.

Regards
Alexander

**Comment by riebl** [comment]
Thanks, @awillecke for your work! I have added several commits on top of your branch at riebl:envmod_sensor_abstraction.
Notably, I stumbled once again why `OmniscientSensor` has a field-of-view and had to reread our prior discussion. Possibly `SeeThroughSensor` is a better descriptive name reflecting what this sensor type actually does. What are your thoughts?
Furthermore, the `InterdistanceMatrix` preselection did not play nice with rear sensors. This misbehaviour is fixed as well now.
I would be happy about hearing your feedback before merging envmod_sensor_abstraction into master :-)

**Comment by awillecke** [comment]
Hi Raphael,

thank you for reviewing my suggestion and improving upon it. 

I'm also fine with the `SeeThroughSensor` instead of the `OmniscientSensor`. Since it has a radius it is not really that omniscient :) Also, moving the sensor visualization from XML to the NED is a nice change, cleaning up the configuration.

We noticed the rear sensor bug when using `InterdistanceMatrix` in the master as well but did not find any time to fix it ourselves.

Thank you and kind regards
Alexander

**Comment by riebl** [comment]
Rebased and merged into master branch :-) Thanks again for your work!

**Pull request closed without merging**
