### PR TITLE
RSUs with multiple antennas

### PR DESCRIPTION
**Pull request by awillecke**
With this pull request, RSUs can be defined in a separate XML file. Additionally, each RSU can be equipped with multiple radios and directional antennas, aiming down different lanes of the junction instead of using a single omnidirectional antenna. This way it is possible for RSUs to send and receive frames on specific lanes.

It also includes the `rsu_grid` scenario to provide an example application. To help with placement of RSUs, the`RSUGenerator.py` is included. It places a RSU in the center of each junction of a given SUMO network file. Also, each RSU is automatically equipped with a radio for each outgoing edge of the junction.

### CODE REVIEW

**Comment by riebl** [comment]
@awillecke Thanks a lot for your contributions! I will review your PR as soon as possible but this may take a few more days.

**Comment by riebl** [comment]
@awillecke I have reviewed your PR and added my proposed changes to my `wip/directional_rsu` branch. Please have a look at it. If those changes are fine for you as well, I will tidy up this branch and merge it into `master` branch.

My most significant change is the introduction of `StaticNodeManager` for handling of static nodes because it is not related to TraCI at all. I have also reverted several unnecessary changes when the same effect could be achieved by existing mechanisms.

**Comment by awillecke** [comment]
Thanks for reviewing and improving my pull request. The idea to introduce a separate manager class for static nodes makes sense to me.

You also added the the module name generation from the junction ID. I'd suggest to generalize it even more and replace the `junctionID` attribute of the `rsu` with a generic `ID` in case RSUs  are used in other situations.

Additionally, I would like to add the `startTime` of Artery's core to the insertion delay such that RSUs are created in the same time period as vehicles.

I've also changed the path loss model of the example for now, since the assertion bug is triggered  more often with RSUs.

**Comment by riebl** [comment]
@awillecke Your PR is included in 7b88fa3714efb3b7f3638b9282909905db26a34c

**Pull request closed without merging**
